version: '3.8'  

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  
